# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 401)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        MainWindow.setWindowTitle("Algorithmes")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 381))
        self.tabWidget.setObjectName("tabWidget")
        self.sorting = QtWidgets.QWidget()
        self.sorting.setObjectName("sorting")
        self.radioRandom = QtWidgets.QRadioButton(self.sorting)
        self.radioRandom.setGeometry(QtCore.QRect(180, 0, 111, 17))
        self.radioRandom.setChecked(True)
        self.radioRandom.setObjectName("radioRandom")
        self.fixedRadioFrame = QtWidgets.QFrame(self.sorting)
        self.fixedRadioFrame.setEnabled(True)
        self.fixedRadioFrame.setGeometry(QtCore.QRect(0, 0, 601, 161))
        self.fixedRadioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fixedRadioFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fixedRadioFrame.setObjectName("fixedRadioFrame")
        self.openFileButton = QtWidgets.QPushButton(self.fixedRadioFrame)
        self.openFileButton.setGeometry(QtCore.QRect(100, 50, 121, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.copyClipboardButton = QtWidgets.QPushButton(self.fixedRadioFrame)
        self.copyClipboardButton.setGeometry(QtCore.QRect(380, 50, 121, 23))
        self.copyClipboardButton.setObjectName("copyClipboardButton")
        self.radioFixed = QtWidgets.QRadioButton(self.sorting)
        self.radioFixed.setGeometry(QtCore.QRect(340, 0, 81, 16))
        self.radioFixed.setObjectName("radioFixed")
        self.randomRadioFrame = QtWidgets.QFrame(self.sorting)
        self.randomRadioFrame.setEnabled(True)
        self.randomRadioFrame.setGeometry(QtCore.QRect(0, 0, 601, 161))
        self.randomRadioFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.randomRadioFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.randomRadioFrame.setObjectName("randomRadioFrame")
        self.arrayLengthEdit = QtWidgets.QLineEdit(self.randomRadioFrame)
        self.arrayLengthEdit.setGeometry(QtCore.QRect(30, 60, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.arrayLengthEdit.setFont(font)
        self.arrayLengthEdit.setObjectName("arrayLengthEdit")
        self.label = QtWidgets.QLabel(self.randomRadioFrame)
        self.label.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.label.setObjectName("label")
        self.randomizeArrayButton = QtWidgets.QPushButton(self.randomRadioFrame)
        self.randomizeArrayButton.setGeometry(QtCore.QRect(250, 110, 101, 23))
        self.randomizeArrayButton.setObjectName("randomizeArrayButton")
        self.randomizedLabel = QtWidgets.QLabel(self.sorting)
        self.randomizedLabel.setGeometry(QtCore.QRect(0, 140, 601, 21))
        self.randomizedLabel.setText("")
        self.randomizedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.randomizedLabel.setObjectName("randomizedLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.sorting)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 160, 601, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bubbleSortButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bubbleSortButton.setObjectName("bubbleSortButton")
        self.gridLayout.addWidget(self.bubbleSortButton, 0, 0, 1, 1)
        self.quickSortButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.quickSortButton.setObjectName("quickSortButton")
        self.gridLayout.addWidget(self.quickSortButton, 1, 0, 1, 1)
        self.mergeSortButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mergeSortButton.setObjectName("mergeSortButton")
        self.gridLayout.addWidget(self.mergeSortButton, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.tabWidget.addTab(self.sorting, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.radioRandom.setText(_translate("MainWindow", "Random Array"))
        self.openFileButton.setText(_translate("MainWindow", "Open File"))
        self.copyClipboardButton.setText(_translate("MainWindow", "Copy From Clipboard"))
        self.radioFixed.setText(_translate("MainWindow", "Fixed Array"))
        self.label.setText(_translate("MainWindow", "Array Længde:"))
        self.randomizeArrayButton.setText(_translate("MainWindow", "Randomize Array"))
        self.bubbleSortButton.setText(_translate("MainWindow", "Bubblesort"))
        self.quickSortButton.setText(_translate("MainWindow", "Quicksort"))
        self.mergeSortButton.setText(_translate("MainWindow", "Mergesort"))
        self.pushButton_5.setText(_translate("MainWindow", "WIP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sorting), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRestart.setText(_translate("MainWindow", "Restart"))

